// Code generated by protoc-gen-defaults. DO NOT EDIT.

package example

import "go.uber.org/zap/zapcore"

func (u *User) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddString("PhysicalDesk:", u.PhysicalDesk)

	enc.AddObject("Service:", u.Service)

	return nil
}

func (u *ServiceMsg) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddString("Name:", u.Name)

	return nil
}
